theme: jekyll-theme-tactile
title: GTM Ajax Listener
description: "Ajax Listener for Google Tag Manager without JQuery or any dependency requirement. Supports all LunaMetrics
Ajax Listener features."
google_analytics: UA-142479734-2
